# Generated by Django 4.2.4 on 2023-10-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='formato',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AddField(
            model_name='funcion',
            name='idioma',
            field=models.CharField(default='N/A', max_length=25),
        ),
    ]
