# Generated by Django 4.2.4 on 2023-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion_corta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion_larga',
            field=models.CharField(max_length=1500),
        ),
    ]
