# Generated by Django 4.2.4 on 2023-10-20 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('deshabilitado', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador')], default='ADMINISTRADOR', max_length=20),
        ),
    ]
