# Generated by Django 4.2.4 on 2023-10-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funciones', '0002_funcion_formato_funcion_idioma'),
        ('butacas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButacaxFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=0)),
                ('butaca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='butacas.butaca')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funciones.funcion')),
            ],
        ),
    ]
