# Generated by Django 4.2.4 on 2023-10-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion_larga',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='actores',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='distribuidor',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='video_trailer',
        ),
    ]
