# Generated by Django 4.2.4 on 2023-10-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_administrador'),
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cliente'),
        ),
    ]
